### ISSUE TITLE
Support for underscore in shortcode names

### ISSUE THREAD

**Issue by thunderer** [spotman/betakiller#16]
Hi @spotman, I'm an author of the Shortcode library you use in this project. I saw [this comment](https://github.com/spotman/betakiller/blob/18926c4874c1d2afae568ce59ff2488126b07f1a/modules/content/classes/Task/Content/Import/Wordpress.php#L466) in your repository, do you want me to add underscore `_` to the list of allowed characters in shortcode names?

Have you found any other problems or do you have any ideas how I could make Shortcode better? If you find anything, please do submit an issue, I will be happy to help!

**Comment by spotman** [comment]
Hello, Tomasz!

Thank you very much for your interest, I was very impressed by this issue and the attention you paid to my project.

It would be nice to see underscore symbol support in your library coz I will be able to remove [this wierd `str_replace` workaround](https://github.com/spotman/betakiller/blob/18926c4874c1d2afae568ce59ff2488126b07f1a/modules/content/classes/Task/Content/Import/Wordpress.php#L467). I hope it wouldn't take a lot of your time :)

I had only positive experience with your Shortcode library, everything was OK for me except of `_` symbol support. I like your code structure and the code is easy to understand :+1: So I really have no any recommendations for you now :)

**Comment by spotman** [comment]
@thunderer this is a gentle reminder about my reply (in case if you did not received previous notification) . Anyway thanks again for your attention and have a nice weekend!

**Comment by thunderer** [comment]
@spotman Hi, sorry for the delay - I was away from the computer for a weekend. I just checked and underscore `_` *is* supported in shortcode name. The problem is that you have Shortcode `v0.5.3` [in your `composer.lock`](https://github.com/spotman/betakiller/blob/master/composer.lock#L649) - please run `composer update` because the latest version is `v0.6.3`.

Sorry for the mistake, I remembered that I had an issue with this previously, but I fixed it in the past. I guess that's the best kind of errors - the ones you just forgot that are fixed. :)

**Comment by spotman** [comment]
Yep, @thunderer, that's a best ones :+1:

Thank you for pointing me in the right direction, I installed you lib long time ago via Composer example in [README](https://github.com/thunderer/Shortcode/blob/master/README.md) and did not noticed that you've been changed major version, my bad. Now it works :)

May you tell me how did you explored that I'm using your library? Was it a special software or a simple github query?

**Comment by thunderer** [comment]
Someone sent me a link to libraries.io, they have something called "dependent repositories", so I [checked it out](https://libraries.io/packagist/thunderer%2Fshortcode/dependent-repositories). You didn't register `betakiller` on Packagist, so I would need to search GitHub directly, and there are many repositories that have [my whole library committed](https://github.com/search?q=thunder%5Cshortcode&type=Code&utf8=%E2%9C%93), so too much work to filter how it is actually used.

**Comment by spotman** [comment]
@thunderer Thank you so much for this explanation, I'll pay more attention to Packagist next year.

I think this issue is fixed so I'm closing it. Thanks again for your time and have a nice weekend!
